### ISSUE TITLE
Adding Extra command support for chance/random command rewards

### ISSUE THREAD

**Issue by Rexmen1** [Crazy-Crew/CrazyVouchers#79]
### Describe the feature

    random-commands:
      - "tokens give {player} %rng_1000,2500%"
      - "shards give {player} %rng_5,10%"
      - "souls give {player} %rng_250,1000%"
      - "cmi money give {player} %rng_25000,100000%"
      - "addxp {player} Mining %rng_10000,25000%"
      - "addxp {player} Acrobatics %rng_10000,25000%"
      - "addxp {player} Alchemy %rng_10000,25000%"
      
      So was thinking if possible adding some sort of way to add feedback msg for each reward
      something like this or anyway dev thinks best
      - "tokens give {player} %rng_1000,2500% | Msg {player} you got %rng_last_generated% tokens"

**Comment by Houdeeny** [comment]
**+1**! Some commands that I intend to use don't have any feedback, so something like this would be great. Additionally, I'd like to suggest that it works for `chance-commands` as well.

Another possible syntax inspired by CrazyCrates:
```
chance-commands:
  '1':
    Weight: 25
    Commands:
    - exp give {player} 500
    - broadcast {player} has won 500 experience points!
  '2':
    Weight: 25
    Commands:
    - eco give {player} 500
    - broadcast {player} has won $500!
```
This kind of structure would make it easy to add multiple commands and keep things organized.
